// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDNtTZzsFj6CrlayeH65-ejFsAy9aQW6Jk',
    appId: '1:138914182592:web:6db0239146fcbe35534425',
    messagingSenderId: '138914182592',
    projectId: 'biscuitt-21b7d',
    authDomain: 'biscuitt-21b7d.firebaseapp.com',
    storageBucket: 'biscuitt-21b7d.appspot.com',
    measurementId: 'G-67WG2CMWLV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0-Gcro2-YgPSdeDuoiHmXRq9akRteGKg',
    appId: '1:138914182592:android:0ad3a72da157ea12534425',
    messagingSenderId: '138914182592',
    projectId: 'biscuitt-21b7d',
    storageBucket: 'biscuitt-21b7d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyARE_-nHZAo0KV4UHOjUHL4xgj5IwDu2Fk',
    appId: '1:138914182592:ios:f45709ad53e0b656534425',
    messagingSenderId: '138914182592',
    projectId: 'biscuitt-21b7d',
    storageBucket: 'biscuitt-21b7d.appspot.com',
    iosClientId: '138914182592-c3uvak6db3djlcp8pic5afov1u2crlkf.apps.googleusercontent.com',
    iosBundleId: 'com.example.biscuittAi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyARE_-nHZAo0KV4UHOjUHL4xgj5IwDu2Fk',
    appId: '1:138914182592:ios:737f04b9d9dbb75e534425',
    messagingSenderId: '138914182592',
    projectId: 'biscuitt-21b7d',
    storageBucket: 'biscuitt-21b7d.appspot.com',
    iosClientId: '138914182592-orcbda08aa4c5lao9sjo7fcd5ca2hccb.apps.googleusercontent.com',
    iosBundleId: 'com.example.biscuittAi.RunnerTests',
  );
}
